server.port=8081
spring.application.name=module4
spring.datasource.url=jdbc:mysql://localhost:3306/ProdReadyFeatures?useSSl=false
spring.datasource.username=root
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


employeeService.base.url = http://localhost:8080/
#configuring a package to the root
    #logging.level.root = trace

#configuring a packing to logging
logging.level.com.ankit.module4.clients = trace
#formate the logging
logging.pattern.console=%d{dd-mm-yy hh:MM:ss} [%level] [%c{2.}] ---%m%n
#loggin in a file
logging.file.name=application.log

logging.pattern.file= %d{dd-mm-yy hh:MM:ss} [%level] %clr{...}{green} [%c{2.}] ---%m%n