server.port=8081
spring.application.name=module4
spring.datasource.url=jdbc:mysql://localhost:3306/ProdReadyFeatures?useSSl=false
spring.datasource.username=root
spring.datasource.password=123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true


employeeService.base.url=http://localhost:8080/
#configuring a package to the root
#logging.level.root=trace

#configuring a packing to logging
logging.level.root=info
logging.level.com.ankit.module4.clients=trace
#format the logging
logging.pattern.console=%d{dd-MM-yy HH:mm:ss} [%level] [%c{2}] ---%m%n
#log in a file
logging.file.name=application.log

logging.pattern.file=%d{dd-MM-yy HH:mm:ss} [%level] [%c{2}] ---%m%n

#Actuator
management.endpoints.web.exposure.include=*
#add own custom info
management.info.env.enabled=true
info.app.author= Ankit Singh Yadav
info.app.version=21.212
info.app.documentation=http://yadavInfoTech.com
management.endpoint.env.show-values=always
management.info.build.enabled=true
management.info.git.enabled=true
management.info.os.enabled=true
management.info.java.enabled=true

